replicaCount: 1

image:
  repository: youracr.azurecr.io/chat-web
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: LoadBalancer
  port: 3001

namespace: default

env:
  API_URL: "http://localhost:3001"
