apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { .Chart.Name } }
  namespace: { { .Values.namespace } }
spec:
  replicas: { { .Values.replicaCount } }
  selector:
    matchLabels:
      app: { { .Chart.Name } }
  template:
    metadata:
      labels:
        app: { { .Chart.Name } }
    spec:
      containers:
        - name: { { .Chart.Name } }
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: { { .Values.image.pullPolicy } }
          ports:
            - containerPort: { { .Values.service.port } }
          env:
            - name: AZURE_OPENAI_RESOURCE_NAME
              value: { { .Values.env.AZURE_OPENAI_RESOURCE_NAME | quote } }
            - name: AZURE_OPENAI_API_KEY
              value: { { .Values.env.AZURE_OPENAI_API_KEY | quote } }
            - name: AZURE_OPENAI_DEPLOYMENT
              value: { { .Values.env.AZURE_OPENAI_DEPLOYMENT | quote } }
